package com.henrya.tools.htcleaner.cli;

import picocli.CommandLine;

/**
 * Reads the CLI version from the jar manifest generated by Maven or Gradle.
 */
public final class ManifestVersionProvider implements CommandLine.IVersionProvider {
  private static final String UNKNOWN_VERSION = "unknown";

  @Override
  public String[] getVersion() {
    return new String[]{"htcleaner " + resolveVersion()};
  }

  private String resolveVersion() {
    Package commandPackage = ManifestVersionProvider.class.getPackage();
    if (commandPackage == null || commandPackage.getImplementationVersion() == null
        || commandPackage.getImplementationVersion().trim().isEmpty()) {
      return UNKNOWN_VERSION;
    }
    return commandPackage.getImplementationVersion();
  }
}
